# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cccfdd7e6214bbe3c5b3de696c94f23b0e5a809b60ee012b4a290dea84d1d8853f188603d8bbd860257eb8fe824e8f2a25ece3ee7bec69bf8b54b4d8b6f20f8a

test:
  secret_key_base: a06f33e8a0ec61b4607f34b71d55d182542cd10a7e70e0dcdd47905699ff5581a220747719916d17df5f7b111e840dddb5fed46882565562b9e4b81bbfc320f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
